### ISSUE TITLE
Crash after reboot on Android O

### ISSUE THREAD

**Issue by biokys** [foursquare/pilgrimsdk-docs-public#1]
Hi, 
we have crashes on Android O:

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.foursquare.pilgrim.ReceiverPilgrimBootFire: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.droid4you.application.wallet/com.foursquare.pilgrim.PilgrimBootService (has extras) }: app is in background uid UidRecord{4848fd u0a107 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.droid4you.application.wallet/com.foursquare.pilgrim.PilgrimBootService (has extras) }: app is in background uid UidRecord{4848fd u0a107 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(SourceFile:99)
       at com.foursquare.pilgrim.ReceiverPilgrimBootFire.onReceive(SourceFile:22)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by rkotzy** [comment]
Hey @biokys, this should be resolved in version 1.1.10 (released today)

[https://github.com/foursquare/pilgrimsdk-docs-public/wiki/Changelog#1110](https://github.com/foursquare/pilgrimsdk-docs-public/wiki/Changelog#1110)
